package commandmeta

import (
	"fmt"
	"sort"
	"strings"
)

// Zsh renders a deterministic native completion definition for both installed
// command names. The file is suitable for a compinit-managed $fpath directory.
func Zsh() string {
	var output strings.Builder
	output.WriteString("#compdef hextap brew-hextap\n\n")
	output.WriteString("# Generated by `hextap completion zsh`; do not hand-edit.\n")
	output.WriteString("# Help and completion share internal/commandmeta as their source of truth.\n")
	output.WriteString("# The documentation appendix mirrors every detailed help field.\n\n")
	writeDocumentation(&output, rootCommand, nil)
	writeEnumHelpers(&output, rootCommand, nil)
	writeCommandFunctions(&output, rootCommand, nil)
	output.WriteString("_hextap \"$@\"\n")
	return output.String()
}

func writeDocumentation(output *strings.Builder, command Command, path []string) {
	name := strings.TrimSpace(strings.Join(append([]string{"hextap"}, path...), " "))
	fmt.Fprintf(output, "# Command: %s\n", commentText(name))
	fmt.Fprintf(output, "# Purpose: %s\n", commentText(command.Summary))
	fmt.Fprintf(output, "# Description: %s\n", commentText(command.Description))
	for _, argument := range command.Arguments {
		qualifier := "optional"
		if argument.Required {
			qualifier = "required"
		}
		if argument.Repeatable {
			qualifier += ", repeatable"
		}
		fmt.Fprintf(output, "# Argument %s (%s): %s\n", commentText(argument.Name), qualifier, commentText(argument.Description))
	}
	for _, note := range command.Safety {
		fmt.Fprintf(output, "# Safety: %s\n", commentText(note))
	}
	for _, example := range command.Examples {
		fmt.Fprintf(output, "# Example: %s\n", commentText(example.Description))
		fmt.Fprintf(output, "#   %s\n", commentText(strings.ReplaceAll(example.Command, "{command}", "hextap")))
	}
	output.WriteByte('\n')
	for _, child := range command.Children {
		childPath := append(append([]string(nil), path...), child.Name)
		writeDocumentation(output, child, childPath)
	}
}

func writeEnumHelpers(output *strings.Builder, command Command, path []string) {
	for _, option := range command.Options {
		if (option.Kind != EnumValue && option.Kind != BoolValue) || len(option.Choices) == 0 {
			continue
		}
		fmt.Fprintf(output, "%s() {\n", enumFunction(path, option.Long))
		output.WriteString("  local context state state_descr line\n")
		output.WriteString("  typeset -A val_args\n")
		fmt.Fprintf(output, "  _values %s \\\n", shellQuote(strings.ToLower(option.ValueName)))
		for index, choice := range option.Choices {
			suffix := " \\\n"
			if index == len(option.Choices)-1 {
				suffix = "\n"
			}
			fmt.Fprintf(output, "    %s%s", shellQuote(choice.Name+"["+zshDescription(choice.Description)+"]"), suffix)
		}
		output.WriteString("}\n\n")
	}
	for _, child := range command.Children {
		childPath := append(append([]string(nil), path...), child.Name)
		writeEnumHelpers(output, child, childPath)
	}
}

func writeCommandFunctions(output *strings.Builder, command Command, path []string) {
	for _, child := range command.Children {
		childPath := append(append([]string(nil), path...), child.Name)
		writeCommandFunctions(output, child, childPath)
	}

	function := commandFunction(path)
	fmt.Fprintf(output, "%s() {\n", function)
	output.WriteString("  local context state state_descr line\n")
	output.WriteString("  typeset -A opt_args\n")
	if len(command.Children) != 0 {
		output.WriteString("  _arguments -C \\\n")
	} else {
		output.WriteString("  _arguments -S \\\n")
	}
	writeOptionSpecs(output, path, command.Options, len(command.Children) == 0)
	if len(command.Children) == 0 {
		output.WriteString("}\n\n")
		return
	}
	output.WriteString("    '1:command:->command' \\\n")
	output.WriteString("    '*::argument:->arguments'\n")
	output.WriteString("  case \"$state\" in\n")
	output.WriteString("    command)\n")
	output.WriteString("      local -a commands\n")
	output.WriteString("      commands=(\n")
	for _, child := range command.Children {
		fmt.Fprintf(output, "        %s\n", shellQuote(child.Name+":"+zshDescription(child.Summary)))
	}
	output.WriteString("      )\n")
	output.WriteString("      _describe 'command' commands\n")
	output.WriteString("      ;;\n")
	output.WriteString("    arguments)\n")
	output.WriteString("      case \"${line[1]}\" in\n")
	for _, child := range command.Children {
		childPath := append(append([]string(nil), path...), child.Name)
		fmt.Fprintf(output, "        %s) %s ;;\n", child.Name, commandFunction(childPath))
	}
	output.WriteString("      esac\n")
	output.WriteString("      ;;\n")
	output.WriteString("  esac\n")
	output.WriteString("}\n\n")
}

func writeOptionSpecs(output *strings.Builder, path []string, options []Option, terminal bool) {
	type rendered struct {
		option Option
		form   string
	}
	var specs []rendered
	for _, option := range options {
		specs = append(specs, rendered{option: option, form: "-" + option.Short}, rendered{option: option, form: "--" + option.Long})
	}
	for index, item := range specs {
		option := item.option
		prefix := "(" + "-" + option.Short + " --" + option.Long + ")"
		if option.Repeatable {
			prefix = "*"
		}
		spec := prefix + item.form
		if option.Kind == BoolValue {
			spec += "=-"
		}
		spec += "[" + zshDescription(option.Description) + "]"
		if option.ValueName != "" {
			separator := ":"
			if option.Optional {
				separator = "::"
			}
			spec += separator + strings.ToLower(option.ValueName) + ":" + zshAction(path, option)
		}
		suffix := " \\\n"
		if terminal && index == len(specs)-1 {
			suffix = "\n"
		}
		fmt.Fprintf(output, "    %s%s", shellQuote(spec), suffix)
	}
	if terminal && len(specs) == 0 {
		output.WriteString("    '*:argument:'\n")
	}
}

func zshAction(path []string, option Option) string {
	switch option.Kind {
	case DirectoryValue:
		return "_directories"
	case FileValue:
		return "_files"
	case EnumValue:
		return enumFunction(path, option.Long)
	case BoolValue:
		return enumFunction(path, option.Long)
	default:
		return "_message \"" + strings.ReplaceAll(strings.ToLower(option.ValueName), "\"", "") + "\""
	}
}

func commandFunction(path []string) string {
	if len(path) == 0 {
		return "_hextap"
	}
	return "_hextap_" + strings.ReplaceAll(strings.Join(path, "_"), "-", "_")
}

func enumFunction(path []string, option string) string {
	parts := append(append([]string{"_hextap_values"}, path...), option)
	for index := range parts {
		parts[index] = strings.ReplaceAll(parts[index], "-", "_")
	}
	return strings.Join(parts, "_")
}

func zshDescription(value string) string {
	value = strings.Join(strings.Fields(value), " ")
	replacer := strings.NewReplacer(
		"\\", "\\\\",
		"[", "\\[",
		"]", "\\]",
		":", "\\:",
	)
	return replacer.Replace(value)
}

func commentText(value string) string {
	return strings.Join(strings.Fields(value), " ")
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

// SortedPaths returns every command path in deterministic lexical order. It is
// useful to consumers that need an exhaustive coverage check.
func SortedPaths() [][]string {
	var paths [][]string
	var collect func(Command, []string)
	collect = func(command Command, path []string) {
		paths = append(paths, append([]string(nil), path...))
		for _, child := range command.Children {
			collect(child, append(append([]string(nil), path...), child.Name))
		}
	}
	collect(rootCommand, nil)
	sort.Slice(paths, func(i, j int) bool {
		return strings.Join(paths[i], "\x00") < strings.Join(paths[j], "\x00")
	})
	return paths
}
